/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgentMarket {
  export type AgentStruct = {
    id: BigNumberish;
    creator: AddressLike;
    owner: AddressLike;
    mintPrice: BigNumberish;
    usageCount: BigNumberish;
    listed: boolean;
    price: BigNumberish;
    role: string;
    metadataURI: string;
  };

  export type AgentStructOutput = [
    id: bigint,
    creator: string,
    owner: string,
    mintPrice: bigint,
    usageCount: bigint,
    listed: boolean,
    price: bigint,
    role: string,
    metadataURI: string
  ] & {
    id: bigint;
    creator: string;
    owner: string;
    mintPrice: bigint;
    usageCount: bigint;
    listed: boolean;
    price: bigint;
    role: string;
    metadataURI: string;
  };
}

export interface AgentMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentExists"
      | "agents"
      | "allAgentIds"
      | "burnAgent"
      | "buyAgent"
      | "costPerUse"
      | "getAgentsByRole"
      | "listAgent"
      | "marketOwner"
      | "mintAgent"
      | "mintFee"
      | "unlistAgent"
      | "useAgent"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentBought"
      | "AgentBurned"
      | "AgentListed"
      | "AgentMinted"
      | "AgentUsed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allAgentIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "costPerUse",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentsByRole",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "listAgent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintAgent",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "mintFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unlistAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "useAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "agentExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allAgentIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burnAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "costPerUse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentsByRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unlistAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "useAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace AgentBoughtEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    oldOwner: AddressLike,
    newOwner: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    oldOwner: string,
    newOwner: string,
    price: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    oldOwner: string;
    newOwner: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentBurnedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    refundAmount: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    owner: string,
    refundAmount: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentListedEvent {
  export type InputTuple = [agentId: BigNumberish, price: BigNumberish];
  export type OutputTuple = [agentId: bigint, price: bigint];
  export interface OutputObject {
    agentId: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentMintedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    creator: AddressLike,
    role: string
  ];
  export type OutputTuple = [agentId: bigint, creator: string, role: string];
  export interface OutputObject {
    agentId: bigint;
    creator: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUsedEvent {
  export type InputTuple = [agentId: BigNumberish, caller: AddressLike];
  export type OutputTuple = [agentId: bigint, caller: string];
  export interface OutputObject {
    agentId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentMarket extends BaseContract {
  connect(runner?: ContractRunner | null): AgentMarket;
  waitForDeployment(): Promise<this>;

  interface: AgentMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentExists: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  agents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        string,
        string
      ] & {
        id: bigint;
        creator: string;
        owner: string;
        mintPrice: bigint;
        usageCount: bigint;
        listed: boolean;
        price: bigint;
        role: string;
        metadataURI: string;
      }
    ],
    "view"
  >;

  allAgentIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  burnAgent: TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;

  buyAgent: TypedContractMethod<[agentId: BigNumberish], [void], "payable">;

  costPerUse: TypedContractMethod<[], [bigint], "view">;

  getAgentsByRole: TypedContractMethod<
    [role: string],
    [AgentMarket.AgentStructOutput[]],
    "view"
  >;

  listAgent: TypedContractMethod<
    [agentId: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  marketOwner: TypedContractMethod<[], [string], "view">;

  mintAgent: TypedContractMethod<
    [role: string, metadataURI: string],
    [void],
    "payable"
  >;

  mintFee: TypedContractMethod<[], [bigint], "view">;

  unlistAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  useAgent: TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentExists"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        string,
        string
      ] & {
        id: bigint;
        creator: string;
        owner: string;
        mintPrice: bigint;
        usageCount: bigint;
        listed: boolean;
        price: bigint;
        role: string;
        metadataURI: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "allAgentIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "burnAgent"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "buyAgent"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "costPerUse"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentsByRole"
  ): TypedContractMethod<
    [role: string],
    [AgentMarket.AgentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "listAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "marketOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mintAgent"
  ): TypedContractMethod<
    [role: string, metadataURI: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unlistAgent"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "useAgent"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentBought"
  ): TypedContractEvent<
    AgentBoughtEvent.InputTuple,
    AgentBoughtEvent.OutputTuple,
    AgentBoughtEvent.OutputObject
  >;
  getEvent(
    key: "AgentBurned"
  ): TypedContractEvent<
    AgentBurnedEvent.InputTuple,
    AgentBurnedEvent.OutputTuple,
    AgentBurnedEvent.OutputObject
  >;
  getEvent(
    key: "AgentListed"
  ): TypedContractEvent<
    AgentListedEvent.InputTuple,
    AgentListedEvent.OutputTuple,
    AgentListedEvent.OutputObject
  >;
  getEvent(
    key: "AgentMinted"
  ): TypedContractEvent<
    AgentMintedEvent.InputTuple,
    AgentMintedEvent.OutputTuple,
    AgentMintedEvent.OutputObject
  >;
  getEvent(
    key: "AgentUsed"
  ): TypedContractEvent<
    AgentUsedEvent.InputTuple,
    AgentUsedEvent.OutputTuple,
    AgentUsedEvent.OutputObject
  >;

  filters: {
    "AgentBought(uint256,address,address,uint256)": TypedContractEvent<
      AgentBoughtEvent.InputTuple,
      AgentBoughtEvent.OutputTuple,
      AgentBoughtEvent.OutputObject
    >;
    AgentBought: TypedContractEvent<
      AgentBoughtEvent.InputTuple,
      AgentBoughtEvent.OutputTuple,
      AgentBoughtEvent.OutputObject
    >;

    "AgentBurned(uint256,address,uint256)": TypedContractEvent<
      AgentBurnedEvent.InputTuple,
      AgentBurnedEvent.OutputTuple,
      AgentBurnedEvent.OutputObject
    >;
    AgentBurned: TypedContractEvent<
      AgentBurnedEvent.InputTuple,
      AgentBurnedEvent.OutputTuple,
      AgentBurnedEvent.OutputObject
    >;

    "AgentListed(uint256,uint256)": TypedContractEvent<
      AgentListedEvent.InputTuple,
      AgentListedEvent.OutputTuple,
      AgentListedEvent.OutputObject
    >;
    AgentListed: TypedContractEvent<
      AgentListedEvent.InputTuple,
      AgentListedEvent.OutputTuple,
      AgentListedEvent.OutputObject
    >;

    "AgentMinted(uint256,address,string)": TypedContractEvent<
      AgentMintedEvent.InputTuple,
      AgentMintedEvent.OutputTuple,
      AgentMintedEvent.OutputObject
    >;
    AgentMinted: TypedContractEvent<
      AgentMintedEvent.InputTuple,
      AgentMintedEvent.OutputTuple,
      AgentMintedEvent.OutputObject
    >;

    "AgentUsed(uint256,address)": TypedContractEvent<
      AgentUsedEvent.InputTuple,
      AgentUsedEvent.OutputTuple,
      AgentUsedEvent.OutputObject
    >;
    AgentUsed: TypedContractEvent<
      AgentUsedEvent.InputTuple,
      AgentUsedEvent.OutputTuple,
      AgentUsedEvent.OutputObject
    >;
  };
}
